import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";

import BestSeller from "../components/Home/BestSeller";
import Contact from "../components/Home/Contact";
import Customize from "../components/Home/Customize";
import HeroSection from "../components/Home/HeroSection";
import NewArrivals from "../components/Home/NewArrivals";
import Promise from "../components/Home/Promise";
import ShopBy from "../components/Home/ShopBy";
import Reviews from "../components/Home/Reviews";

import { RefreshUser } from "../redux/Actions/UserActions";
import axios from "axios";
import { useQuery } from "react-query";

export default function Home() {
  const dispatch = useDispatch();
  const userData = useSelector((state) => state.user);
  // console.log(JSON.parse(localStorage.getItem("user_data")));
  console.log(userData);
  useEffect(() => {
    if (userData?.isLoggedIn === false) return;

    //this thunk implementation is to just ensure that if there are any changes in userdata we refresh the data
    dispatch(RefreshUser(userData?.userData?.savedUser?._id, userData));
  }, []);

  return (
    <div>
      <Head>
        <title>Pednekar Jwellery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero section */}
      <HeroSection />
      {/* Best seller */}
      <BestSeller />
      {/* Ads section */}

      {/* New arrival */}
      <NewArrivals />

      {/* Shop by price */}
      <ShopBy />

      <Customize />
      <Reviews />
      <Promise />

      <Contact />
    </div>
  );
}
